import threading
import time
import random
from Characterization.Environment import env
from util.DataFrame import globalFrame
from AutomatedApplication.application.homeApplication import *

BedroomOne_device_list = [
    [deviceOn, ["BedroomOne", "Curtain001"]],
    [deviceOff, ["BedroomOne", "Curtain001"]],
    [deviceOn, ["BedroomOne", "Door001"]],
    [deviceOff, ["BedroomOne", "Door001"]],
    [deviceOn, ["BedroomOne", "AC001"]],
    [deviceOff, ["BedroomOne", "AC001"]],
    [deviceOn, ["BedroomOne", "AirPurifier001"]],
    [deviceOff, ["BedroomOne", "AirPurifier001"]],
    [deviceOn, ["BedroomOne", "Light001"]],
    [deviceOff, ["BedroomOne", "Light001"]],
    [deviceOn, ["BedroomOne", "Humidifier001"]],
    [deviceOff, ["BedroomOne", "Humidifier001"]],
    [deviceOn, ["BedroomOne", "Window001"]],
    [deviceOff, ["BedroomOne", "Window001"]]],

BedroomTwo_device_list = [
    [deviceOn, ["BedroomTwo", "Curtain001"]],
    [deviceOff, ["BedroomTwo", "Curtain001"]],
    [deviceOn, ["BedroomTwo", "Door001"]],
    [deviceOff, ["BedroomTwo", "Door001"]],
    [deviceOn, ["BedroomTwo", "AC001"]],
    [deviceOff, ["BedroomTwo", "AC001"]],
    [deviceOn, ["BedroomTwo", "AirPurifier001"]],
    [deviceOff, ["BedroomTwo", "AirPurifier001"]],
    [deviceOn, ["BedroomTwo", "Light001"]],
    [deviceOff, ["BedroomTwo", "Light001"]],
    [deviceOn, ["BedroomTwo", "Humidifier001"]],
    [deviceOff, ["BedroomTwo", "Humidifier001"]],
    [deviceOn, ["BedroomTwo", "Window001"]],
    [deviceOff, ["BedroomTwo", "Window001"]],
    [deviceOn, ["BedroomTwo", "Window002"]],
    [deviceOff, ["BedroomTwo", "Window002"]],
    [deviceOn, ["BedroomTwo", "TV001"]],
    [deviceOff, ["BedroomTwo", "TV001"]]],

LivingRoom_device_list = [
    [deviceOn, ["LivingRoom", "Curtain001"]],
    [deviceOff, ["LivingRoom", "Curtain001"]],
    [deviceOn, ["LivingRoom", "Door001"]],
    [deviceOff, ["LivingRoom", "Door001"]],
    [deviceOn, ["LivingRoom", "AC001"]],
    [deviceOff, ["LivingRoom", "AC001"]],
    [deviceOn, ["LivingRoom", "AirPurifier001"]],
    [deviceOff, ["LivingRoom", "AirPurifier001"]],
    [deviceOn, ["LivingRoom", "Light001"]],
    [deviceOff, ["LivingRoom", "Light001"]],
    [deviceOn, ["LivingRoom", "Humidifier001"]],
    [deviceOff, ["LivingRoom", "Humidifier001"]],
    [deviceOn, ["LivingRoom", "Window001"]],
    [deviceOff, ["LivingRoom", "Window001"]]],
    
def personOne():
  pool = []
  time.sleep(random.uniform(0.6*60*7.5, 0.6*60*7.7))
  t1 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Light001", env, 'User Activity',))
  t1.start()
  pool.append(t1)
  time.sleep(random.uniform(0.6*10, 0.6*15))
  t2 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t2.start()
  pool.append(t2)
  time.sleep(random.uniform(0.05, 0.1))
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  stateDecrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  time.sleep(random.uniform(0.1, 0.2))
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.1, 0.2))
  toilet = threading.Thread(target=goToilet)
  toilet.start()
  toilet.join()
  time.sleep(random.uniform(0.1, 0.15))
  t9 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t9.start()
  pool.append(t9)
  time.sleep(random.uniform(0.03, 0.05))
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.1, 0.2))
  stateIncrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.6*5, 0.6*8))
  t10 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Light001", env, 'User Activity',))
  t10.start()
  pool.append(t10)
  time.sleep(random.uniform(0.08, 0.1))
  if(random.randint(0, 3) == 1):
    t10 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Curtain001", env, 'User Activity',))
    t10.start()
    pool.append(t10)
  t11 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t11.start()
  pool.append(t11)
  time.sleep(random.uniform(0.05, 0.1))
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  stateDecrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t12.start()
  pool.append(t12)
  time.sleep(random.uniform(0.1, 0.2))
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.1, 0.2))
  cook = threading.Thread(target=Cook)
  cook.start()
  cook.join()
  time.sleep(random.uniform(0.6*10, 0.6*13)) 
  change_clothes = threading.Thread(target=changeClothes)
  change_clothes.start()
  change_clothes.join()
  time.sleep(random.uniform(0.03, 0.05))
  t1 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
  t1.start()
  pool.append(t1)
  time.sleep(random.uniform(0.03, 0.05))
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.6*0.4, 0.6*1.5))
  t2 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
  t2.start()  
  pool.append(t2)
  time.sleep(random.uniform(0.6*60*1.4, 0.6*60*1.5))
  if(random.randint(0, 2) == 1):
    get_up = threading.Thread(target=getUp, args=("BedroomTwo",))
    get_up.start()
    get_up.join()
  time.sleep(random.uniform(0.6*60*1.4, 0.6*60*1.5))
  # 上班
  if(random.randint(0, 3) == 1): # 午休回家
    t3 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t3.start()
    pool.append(t3)
    time.sleep(random.uniform(0.03, 0.05))
    stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
    t4 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t4.start()  
    pool.append(t4)
    time.sleep(random.uniform(0.1, 0.15))
    random_device = random.randint(0, len(LivingRoom_device_list)-1)
    t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
    t.start()
    pool.append(t)    
    time.sleep(random.uniform(0.1, 0.2))
    temp = random.randint(0, 3) == 1
    if(temp == 1):
      time.sleep(random.uniform(0.1, 0.2))
      cook = threading.Thread(target=Cook)
      cook.start()
      cook.join()
      time.sleep(random.uniform(0.6*15, 0.6*20))
      
    t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
    t.start()
    pool.append(t)
    time.sleep(random.uniform(0.03, 0.05))
    stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
    stateIncrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
    time.sleep(random.uniform(0.03, 0.05))
    t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
    t.start()  
    pool.append(t)
    if temp == 1:
      time.sleep(random.uniform(0.6*75, 0.6*80))
    else:
      time.sleep(random.uniform(0.6*90, 0.6*100))
    random_device = random.randint(0, len(BedroomTwo_device_list)-1)
    t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
    t.start()
    pool.append(t)    
    time.sleep(random.uniform(0.1, 0.2))
    t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
    t.start()
    pool.append(t)
    time.sleep(random.uniform(0.03, 0.05))
    stateDecrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
    stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
    time.sleep(random.uniform(0.03, 0.05))
    t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
    t.start()  
    pool.append(t)
    time.sleep(random.uniform(0.1, 0.15))
    
    # 14.00
    t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t.start()
    pool.append(t)
    time.sleep(random.uniform(0.03, 0.05))
    stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
    time.sleep(random.uniform(0.3, 0.6*1.5))
    t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t.start()  
    pool.append(t)
    time.sleep(random.uniform(0.6*60*4.2, 0.6*4.5))
  else:
    time.sleep(random.uniform(0.6*60*6, 0.6*6.2))
  # 18.00-18.30
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
  t.start()  
  pool.append(t)
  time.sleep(random.uniform(0.1, 0.2)) 
  cook = threading.Thread(target=Cook)
  cook.start()
  cook.join()
  time.sleep(random.uniform(0.6*15, 0.6*20)) 
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.6*15, 0.6*20))   
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.6*20, 0.6*30))   
  change_clothes = threading.Thread(target=changeClothes)
  change_clothes.start()
  change_clothes.join()
  time.sleep(random.uniform(0.1, 0.2))
  t1 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Window001", env, 'User Activity',))
  t1.start()
  pool.append(t1)
  time.sleep(random.uniform(0.1, 0.2))
  start_time = random.uniform(40*0.6, 90*0.6)
  random_event = threading.Thread(target=Reservation, args=(start_time,))
  random_event.start()
  pool.append(random_event)
  if random.randint(0, 50) < 45: 
      time.sleep(start_time - 5*0.6)
      washing = threading.Thread(target=Washing)
      washing.start()
      washing.join()
      time.sleep(random.uniform(0.03, 0.05))
  else:
    time.sleep(random.uniform(0.6*25, 0.6*30))  
  time.sleep(random.uniform(0.6*25, 0.6*30))
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.1, 0.2))
  stateIncrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.6*10, 0.6*15))  
  random_device = random.randint(0, len(BedroomTwo_device_list)-1)
  t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)  
  if(random.randint(0, 3) == 1):   
    time.sleep(random.uniform(0.6*10, 0.6*11))   
    wash_clothes = threading.Thread(target=washClothes)
    wash_clothes.start()
    wash_clothes.join()
    time.sleep(random.uniform(0.6*20, 0.6*50))  
    collect_clothes = threading.Thread(target=collectClothes)
    collect_clothes.start()
    collect_clothes.join()
  else:
    time.sleep(random.uniform(0.6*30, 0.6*60))  
  random_device = random.randint(0, len(BedroomTwo_device_list)-1)
  t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  stateDecrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  if(random.randint(0, 2) == 1):   
    start_time = random.uniform(40*0.6, 90*0.6)
    random_event = threading.Thread(target=Reservation, args=(start_time,))
    random_event.start()
    pool.append(random_event)
    if random.randint(0, 50) < 40: 
        time.sleep(start_time - 5*0.6)
        washing = threading.Thread(target=Washing)
        washing.start()
        washing.join()
        time.sleep(random.uniform(0.03, 0.05))
    else:
      time.sleep(random.uniform(0.6*25, 0.6*30))  
  else:
    time.sleep(random.uniform(0.6*25, 0.6*30))
  tv = threading.Thread(target=watchTV)
  tv.start()
  tv.join()
  time.sleep(random.uniform(0.6*2, 0.6*3))
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  stateIncrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.6*40, 0.6*45))  
  if(random.randint(0, 2) == 1):
    t12 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Heater001", env, 'User Activity',))
    t12.start()
    pool.append(t12) 
    time.sleep(random.uniform(0.6*10, 0.6*11))
    stateDecrease(globalFrame.thread_list,"BedroomTwo", "Humidity", env)
  if(random.randint(0, 2) == 1):
    t12 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Window001", env, 'User Activity',))
    t12.start()
    pool.append(t12)  
    time.sleep(random.uniform(0.1, 0.2))
  if(random.randint(0, 2) == 1):
    t12 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Window002", env, 'User Activity',))
    t12.start()
    pool.append(t12)  
    time.sleep(random.uniform(0.1, 0.2))
  random_device = random.randint(0, len(BedroomTwo_device_list)-1)
  t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.6*40, 0.6*50))  
  random_device = random.randint(0, len(BedroomTwo_device_list)-1)
  t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  if(random.randint(0, 2) == 1):
    time.sleep(random.uniform(0.1, 0.2))
    t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Curtain001", env, 'User Activity',))
    t12.start()
    pool.append(t12)  
  time.sleep(random.uniform(0.6*10, 0.6*11))  
  t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Window001", env, 'User Activity',))
  t12.start()
  pool.append(t12)  
  time.sleep(random.uniform(0.1, 0.2))
  if(random.randint(0, 1) == 1):
    t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Window002", env, 'User Activity',))
    t12.start()
    pool.append(t12)  
    time.sleep(random.uniform(0.1, 0.2))
  random_device = random.randint(0, len(BedroomTwo_device_list)-1)
  t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.1, 0.2))
  t1 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Light001", env, 'User Activity',))
  t1.start()
  pool.append(t1)
  
  for item in pool:
    item.join()
   
def personTwo():
  pool = []
  time.sleep(random.uniform(0.6*60*8, 0.6*60*8.2))
  if(random.randint(0, 4) == 1):
    get_up = threading.Thread(target=getUp, args=("BedroomTwo",))
    get_up.start()
    get_up.join()
  time.sleep(random.uniform(0.1, 0.2))
  if(random.randint(0, 3) == 1):
    t12 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Window001", env, 'User Activity',))
    t12.start()
    pool.append(t12)  
    time.sleep(random.uniform(0.6*10, 0.6*11))
    t12 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Heater001", env, 'User Activity',))
    t12.start()
    pool.append(t12) 
    time.sleep(random.uniform(0.1, 0.2))
    stateDecrease(globalFrame.thread_list,"BedroomTwo", "Humidity", env)
  time.sleep(random.uniform(0.1, 0.2))
  t1 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Light001", env, 'User Activity',))
  t1.start()
  pool.append(t1)
  time.sleep(random.uniform(0.6*10, 0.6*15))
  random_device = random.randint(0, len(BedroomTwo_device_list)-1)
  t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)   
  time.sleep(random.uniform(0.1, 0.2)) 
  t2 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t2.start()
  pool.append(t2)
  time.sleep(random.uniform(0.05, 0.1))
  stateDecrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.1, 0.2))
  toilet = threading.Thread(target=goToilet)
  toilet.start()
  toilet.join()
  time.sleep(random.uniform(0.1, 0.15))
  t9 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t9.start()
  pool.append(t9)
  time.sleep(random.uniform(0.03, 0.05))
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.1, 0.2))
  stateIncrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.6*5, 0.6*8))
  t10 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Light001", env, 'User Activity',))
  t10.start()
  pool.append(t10)
  time.sleep(random.uniform(0.03, 0.05))
  t1 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Window001", env, 'User Activity',))
  t1.start()
  pool.append(t1)
  time.sleep(random.uniform(0.1, 0.2))
  random_device = random.randint(0, len(BedroomTwo_device_list)-1)
  t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.1, 0.2))
  if(random.randint(0, 3) == 1):
    t10 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Curtain001", env, 'User Activity',))
    t10.start()
    pool.append(t10)
  t11 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t11.start()
  pool.append(t11)
  time.sleep(random.uniform(0.05, 0.1))
  stateDecrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t12.start()
  pool.append(t12)
  time.sleep(random.uniform(0.6*10, 0.6*13)) 
  change_clothes = threading.Thread(target=changeClothes)
  change_clothes.start()
  change_clothes.join()
  time.sleep(random.uniform(0.03, 0.05))
  t1 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
  t1.start()
  pool.append(t1)
  time.sleep(random.uniform(0.03, 0.05))
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.1, 0.2))
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.3, 0.6*1.5))
  t2 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
  t2.start()  
  pool.append(t2)
  time.sleep(random.uniform(0.6*60*3, 0.6*60*3.2))
  time.sleep(random.uniform(0.03, 0.05)) 
  # 上班
  if(random.randint(0, 3) == 1): # 午休回家
    t3 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t3.start()
    pool.append(t3)
    time.sleep(random.uniform(0.03, 0.05))
    stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
    t4 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t4.start()  
    pool.append(t4)
    if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Window001", env, 'User Activity',))
      t12.start()
      pool.append(t12)  
    time.sleep(random.uniform(0.03, 0.05))
    random_device = random.randint(0, len(LivingRoom_device_list)-1)
    t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
    t.start()
    pool.append(t)    
    time.sleep(random.uniform(0.1, 0.2))
    if(random.randint(0, 3) <= 1):
      time.sleep(random.uniform(0.6*15, 0.6*20))
      t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
      t.start()
      pool.append(t)
      time.sleep(random.uniform(0.03, 0.05))
      stateIncrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
      stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
      time.sleep(random.uniform(0.03, 0.05))
      t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
      t.start()  
      pool.append(t)
      time.sleep(random.uniform(0.6*5, 0.6*10))
      random_device = random.randint(0, len(BedroomTwo_device_list)-1)
      t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
      t.start()
      pool.append(t)    
      time.sleep(random.uniform(0.6*70, 0.6*71))
      t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
      t.start()
      pool.append(t)
      time.sleep(random.uniform(0.03, 0.05))
      t1 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Humidifier001", env, 'User Activity',))
      t1.start()
      pool.append(t1)
      time.sleep(random.uniform(0.1, 0.2))
      stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
      stateDecrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
      time.sleep(random.uniform(0.03, 0.05))
      t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
      t.start()  
      pool.append(t)
      time.sleep(random.uniform(0.1, 0.15))
    elif random.randint(0, 3) == 2:
      tv = threading.Thread(target=watchTV)
      tv.start()
      tv.join()
      time.sleep(random.uniform(0.1, 0.15))
    # 14.00
    t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t.start()
    pool.append(t)
    time.sleep(random.uniform(0.03, 0.05))
    stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
    time.sleep(random.uniform(0.3, 0.6*1.2))
    t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t.start()  
    pool.append(t)
    time.sleep(random.uniform(0.6*60*4, 0.6*4.5))
  else:
    time.sleep(random.uniform(0.6*60*6, 0.6*6.2))
  # 18.00-18.30
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
  t.start()  
  pool.append(t)
  time.sleep(random.uniform(0.1, 0.2))
  cook = threading.Thread(target=Cook)
  cook.start()
  cook.join()
  time.sleep(random.uniform(0.6*15, 0.6*20)) 
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.6*15, 0.6*20))   
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.6*30, 0.6*45))   
  change_clothes = threading.Thread(target=changeClothes)
  change_clothes.start()
  change_clothes.join()
  time.sleep(random.uniform(0.1, 0.2))
  if(random.randint(0, 2) == 1):   
    start_time = random.uniform(40*0.6, 90*0.6)
    random_event = threading.Thread(target=Reservation, args=(start_time,))
    random_event.start()
    pool.append(random_event)
    if random.randint(0, 50) < 40: 
        time.sleep(start_time - 5*0.6)
        washing = threading.Thread(target=Washing)
        washing.start()
        washing.join()
        time.sleep(random.uniform(0.03, 0.05))
    else:
      time.sleep(random.uniform(0.6*25, 0.6*30))  
  else:
    time.sleep(random.uniform(0.6*25, 0.6*30))  
  time.sleep(random.uniform(0.6*35, 0.6*55))  
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)  
  if random.randint(0, 3) == 1:
    tv = threading.Thread(target=watchTV)
    tv.start()
    tv.join()
  else:
    time.sleep(random.uniform(0.6*65, 0.6*75))  
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  stateIncrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.6*25, 0.6*35))  
  if(random.randint(0, 3) == 1):
      t12 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Heater001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.6*10, 0.6*11))
      stateDecrease(globalFrame.thread_list,"BedroomTwo", "Humidity", env)
  random_device = random.randint(0, len(BedroomTwo_device_list)-1)
  t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.6*20, 0.6*30))  
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Window002", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.03, 0.05))
  random_device = random.randint(0, len(BedroomTwo_device_list)-1)
  t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t) 
  time.sleep(random.uniform(0.03, 0.05))   
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  stateDecrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  toilet = threading.Thread(target=goToilet)
  toilet.start()
  toilet.join()
  time.sleep(random.uniform(0.6*25, 0.6*30))
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Humidifier001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  stateIncrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  if(random.randint(0, 3) == 1):
      t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Heater001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.03, 0.05))
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Humidifier001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.03, 0.05))
  t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Window001", env, 'User Activity',))
  t12.start()
  pool.append(t12) 
  time.sleep(random.uniform(0.6*10, 0.6*15))
  random_device = random.randint(0, len(BedroomTwo_device_list)-1)
  t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t) 
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Light001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.03, 0.05))
  t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Curtain001", env, 'User Activity',))
  t12.start()
  pool.append(t12) 
  time.sleep(random.uniform(0.6*60, 0.6*65))  
  
  for item in pool:
    item.join()

def personThree():
  pool = []
  time.sleep(random.uniform(0.6*60*8, 0.6*60*8.2))
  if(random.randint(0, 2) == 1):
      time.sleep(random.uniform(0.03, 0.05))
      t12 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Window001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
  time.sleep(random.uniform(0.6*10, 0.6*15))
  random_device = random.randint(0, len(BedroomOne_device_list)-1)
  t = threading.Thread(target=BedroomOne_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomOne_device_list[0][random_device][1][0],BedroomOne_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t) 
  time.sleep(random.uniform(0.05, 0.1))
  if(random.randint(0, 5) == 1):
    get_up = threading.Thread(target=getUp, args=("BedroomOne",))
    get_up.start()
    get_up.join()
  t1 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Light001", env, 'User Activity',))
  t1.start()
  pool.append(t1)
  time.sleep(random.uniform(0.6*10, 0.6*15))
  t2 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t2.start()
  pool.append(t2)
  time.sleep(random.uniform(0.05, 0.1))
  stateDecrease(globalFrame.thread_list,"BedroomOne", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.6*25, 0.6*30))
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t) 
  time.sleep(random.uniform(0.05, 0.1))
  t9 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t9.start()
  pool.append(t9)
  time.sleep(random.uniform(0.03, 0.05))
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"BedroomOne", "HumanCount", env)
  time.sleep(random.uniform(0.6*15, 0.6*20))
  t10 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Light001", env, 'User Activity',))
  t10.start()
  pool.append(t10)
  time.sleep(random.uniform(0.03, 0.05))
  t11 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t11.start()
  pool.append(t11)
  time.sleep(random.uniform(0.05, 0.1))
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  stateDecrease(globalFrame.thread_list,"BedroomOne", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t12.start()
  pool.append(t12)
  time.sleep(random.uniform(0.6*15, 0.6*20)) 
  if(random.randint(0, 3) == 1):
    t10 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Curtain001", env, 'User Activity',))
    t10.start()
    pool.append(t10)
  change_clothes = threading.Thread(target=changeClothes)
  change_clothes.start()
  change_clothes.join()
  time.sleep(random.uniform(0.03, 0.05))
  random_device = random.randint(0, len(BedroomOne_device_list)-1)
  t = threading.Thread(target=BedroomOne_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomOne_device_list[0][random_device][1][0],BedroomOne_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t) 
  time.sleep(random.uniform(0.05, 0.1))
  t1 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
  t1.start()
  pool.append(t1)
  time.sleep(random.uniform(0.03, 0.05))
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.3, 0.6*1.5))
  t2 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
  t2.start()  
  pool.append(t2)
  time.sleep(random.uniform(0.6*60*1.5, 0.6*60*1.6))
  if(random.randint(0, 2) == 1):
    get_up = threading.Thread(target=getUp, args=("BedroomOne",))
    get_up.start()
    get_up.join()
  time.sleep(random.uniform(0.6*60*1.5, 0.6*60*1.6))
  # 上班
  if(random.randint(0, 3) == 1): # 午休回家
    t3 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t3.start()
    pool.append(t3)
    time.sleep(random.uniform(0.03, 0.05))
    stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
    t4 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t4.start()  
    pool.append(t4)
    if(random.randint(0, 3) == 1):
      time.sleep(random.uniform(0.6*15, 0.6*20))
      t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
      t.start()
      pool.append(t)
      time.sleep(random.uniform(0.03, 0.05))
      stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
      stateIncrease(globalFrame.thread_list,"BedroomOne", "HumanCount", env)
      time.sleep(random.uniform(0.03, 0.05))
      t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
      t.start()  
      pool.append(t)
      time.sleep(random.uniform(0.6*5, 0.6*10))
      random_device = random.randint(0, len(BedroomOne_device_list)-1)
      t = threading.Thread(target=BedroomOne_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomOne_device_list[0][random_device][1][0],BedroomOne_device_list[0][random_device][1][1], env, 'User Activity',))
      t.start()
      pool.append(t)    
      time.sleep(random.uniform(0.6*70, 0.6*71))
      t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
      t.start()
      pool.append(t)
      time.sleep(random.uniform(0.03, 0.05))
      stateDecrease(globalFrame.thread_list,"BedroomOne", "HumanCount", env)
      stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
      time.sleep(random.uniform(0.03, 0.05))
      t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
      t.start()  
      pool.append(t)
      time.sleep(random.uniform(0.1, 0.15))
    else:
      t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
      t.start()
      pool.append(t)
      time.sleep(random.uniform(0.03, 0.05))
      stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
      stateIncrease(globalFrame.thread_list,"BedroomOne", "HumanCount", env)
      time.sleep(random.uniform(0.03, 0.05))
      t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
      t.start()  
      pool.append(t)
      time.sleep(random.uniform(0.6*5, 0.6*10))
      random_device = random.randint(0, len(BedroomOne_device_list)-1)
      t = threading.Thread(target=BedroomOne_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomOne_device_list[0][random_device][1][0],BedroomOne_device_list[0][random_device][1][1], env, 'User Activity',))
      t.start()
      pool.append(t)    
      time.sleep(random.uniform(0.6*90, 0.6*105))
      t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
      t.start()
      pool.append(t)
      time.sleep(random.uniform(0.03, 0.05))
      stateDecrease(globalFrame.thread_list,"BedroomOne", "HumanCount", env)
      stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
      time.sleep(random.uniform(0.03, 0.05))
    # 14.00
    t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t.start()
    pool.append(t)
    time.sleep(random.uniform(0.03, 0.05))
    stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
    time.sleep(random.uniform(0.3, 0.6*1.5))
    t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t.start()  
    pool.append(t)
    time.sleep(random.uniform(0.6*60*4, 0.6*4.5))
  else:
    time.sleep(random.uniform(0.6*60*6, 0.6*6.2))
  # 18.00-18.30
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
  t.start()  
  pool.append(t)
  time.sleep(random.uniform(0.1, 0.2))
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t) 
  time.sleep(random.uniform(0.05, 0.1))
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Heater001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.6*10, 0.6*11))
      stateDecrease(globalFrame.thread_list,"BedroomTwo", "Humidity", env)
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Window001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.03, 0.05))
  cook = threading.Thread(target=Cook)
  cook.start()
  cook.join()
  time.sleep(random.uniform(0.6*15, 0.6*20)) 
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.6*15, 0.6*20))   
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)  
  if random.randint(0, 3) == 1:
    tv = threading.Thread(target=watchTV)
    tv.start()
    tv.join()
  else:
    time.sleep(random.uniform(0.6*65, 0.6*75))    
  change_clothes = threading.Thread(target=changeClothes)
  change_clothes.start()
  change_clothes.join()
  time.sleep(random.uniform(0.1, 0.2))
  if(random.randint(0, 2) == 1):   
    start_time = random.uniform(40*0.6, 90*0.6)
    random_event = threading.Thread(target=Reservation, args=(start_time,))
    random_event.start()
    pool.append(random_event)
    if random.randint(0, 50) < 40: 
        time.sleep(start_time - 5*0.6)
        washing = threading.Thread(target=Washing)
        washing.start()
        washing.join()
        time.sleep(random.uniform(0.03, 0.05))
    else:
      time.sleep(random.uniform(0.6*25, 0.6*30))  
  else:
    toilet = threading.Thread(target=goToilet)
    toilet.start()
    toilet.join()
  time.sleep(random.uniform(0.6*25, 0.6*30))
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)   
  time.sleep(random.uniform(0.6*50, 0.6*55))   
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Heater001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.6*10, 0.6*11))
      stateDecrease(globalFrame.thread_list,"LivingRoom", "Humidity", env)
  t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Window001", env, 'User Activity',))
  t12.start()
  pool.append(t12) 
  time.sleep(random.uniform(0.03, 0.05))
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"BedroomOne", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.6*25, 0.6*35))  
  random_device = random.randint(0, len(BedroomOne_device_list)-1)
  t = threading.Thread(target=BedroomOne_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomOne_device_list[0][random_device][1][0],BedroomOne_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.6*20, 0.6*30))  
  random_device = random.randint(0, len(BedroomOne_device_list)-1)
  t = threading.Thread(target=BedroomOne_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomOne_device_list[0][random_device][1][0],BedroomOne_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  stateDecrease(globalFrame.thread_list,"BedroomOne", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  toilet = threading.Thread(target=goToilet)
  toilet.start()
  toilet.join()
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  stateIncrease(globalFrame.thread_list,"BedroomOne", "HumanCount", env)
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.6*60, 0.6*70))  
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Curtain001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.03, 0.05))
  t1 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Light001", env, 'User Activity',))
  t1.start()
  pool.append(t1)
  
  for item in pool:
    item.join()
  
def weekendpersonOne():
  pool = []
  time.sleep(random.uniform(0.6*60*8.5, 0.6*60*9))
  get_up = threading.Thread(target=getUp, args=("BedroomTwo",))
  get_up.start()
  get_up.join()
  random_device = random.randint(0, len(BedroomTwo_device_list)-1)
  t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.6*1, 0.6*2))
  random_device = random.randint(0, len(BedroomTwo_device_list)-1)
  t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)  
  time.sleep(random.uniform(0.6*25, 0.6*35))
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Window001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.06, 0.1))
  t2 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t2.start()
  pool.append(t2)
  time.sleep(random.uniform(0.05, 0.1))
  stateDecrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.1, 0.2))
  if(random.randint(0, 2) == 1):   
    start_time = random.uniform(40*0.6, 90*0.6)
    random_event = threading.Thread(target=Reservation, args=(start_time,))
    random_event.start()
    pool.append(random_event)
    if random.randint(0, 50) < 40: 
        time.sleep(start_time - 5*0.6)
        washing = threading.Thread(target=Washing)
        washing.start()
        washing.join()
        time.sleep(random.uniform(0.03, 0.05))
    else:
      time.sleep(random.uniform(0.6*25, 0.6*30))  
  else:
    washing = threading.Thread(target=Washing)
    washing.start()
    washing.join()
  time.sleep(random.uniform(0.6*25, 0.6*30))
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t) 
  time.sleep(random.uniform(0.05, 0.1))
  if(random.randint(0, 4) == 1):
      t12 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Heater001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.6*10, 0.6*11))
      t12 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Window001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.1, 0.2))
      stateDecrease(globalFrame.thread_list,"BedroomTwo", "Humidity", env)
  if(random.randint(0, 5) == 1):
      t12 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Humidifier001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.03, 0.05))
  if random.randint(0, 3) == 1:
    tv = threading.Thread(target=watchTV)
    tv.start()
    tv.join()
  else:
    time.sleep(random.uniform(0.6*65, 0.6*75))   
  t9 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t9.start()
  pool.append(t9)
  time.sleep(random.uniform(0.03, 0.05))
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  time.sleep(random.uniform(0.1, 0.15))
  t10 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Light001", env, 'User Activity',))
  t10.start()
  pool.append(t10)
  time.sleep(random.uniform(0.03, 0.05))
  random_device = random.randint(0, len(BedroomTwo_device_list)-1)
  t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)  
  time.sleep(random.uniform(0.6*10, 0.6*15))
  t11 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t11.start()
  pool.append(t11)
  time.sleep(random.uniform(0.05, 0.1))
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  stateDecrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t12.start()
  pool.append(t12)
  time.sleep(random.uniform(0.6*30, 0.6*35))
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)  
  time.sleep(random.uniform(0.1, 0.2))
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)  
  time.sleep(random.uniform(0.6*30, 0.6*35))
  cook = threading.Thread(target=Cook)
  cook.start()
  cook.join()
  time.sleep(random.uniform(0.6*15, 0.6*20)) 
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Humidifier001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.03, 0.05))
  # 出门3小时
  if(random.randint(0, 3) == 1):
    change_clothes = threading.Thread(target=changeClothes)
    change_clothes.start()
    change_clothes.join()
    time.sleep(random.uniform(0.03, 0.05))
    t1 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t1.start()
    pool.append(t1)
    time.sleep(random.uniform(0.03, 0.05))
    stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
    time.sleep(random.uniform(0.3, 0.6*1.5))
    t2 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t2.start()  
    pool.append(t2)
    time.sleep(random.uniform(0.6*60*2.8, 0.6*60*3))
    t3 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t3.start()
    pool.append(t3)
    time.sleep(random.uniform(0.03, 0.05))
    stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
    t4 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t4.start()  
    pool.append(t4)
  else:
    random_device = random.randint(0, len(LivingRoom_device_list)-1)
    t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
    t.start()
    pool.append(t)  
    time.sleep(random.uniform(0.6*60*1, 0.6*1.5))
    toilet = threading.Thread(target=goToilet)
    toilet.start()
    toilet.join()
    time.sleep(random.uniform(0.6*60*2, 0.6*1.7))
  # 15.30
  time.sleep(random.uniform(0.1, 0.2))
  cook = threading.Thread(target=Cook)
  cook.start()
  cook.join()
  time.sleep(random.uniform(0.6*15, 0.6*20)) 
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)  
  time.sleep(random.uniform(0.6*15, 0.6*20))   
  toilet = threading.Thread(target=goToilet)
  toilet.start()
  toilet.join()
  time.sleep(random.uniform(0.6*15, 0.6*20))   
  if(random.randint(0, 2) == 1):   
    start_time = random.uniform(40*0.6, 90*0.6)
    random_event = threading.Thread(target=Reservation, args=(start_time,))
    random_event.start()
    pool.append(random_event)
    if random.randint(0, 50) < 40: 
        time.sleep(start_time - 5*0.6)
        washing = threading.Thread(target=Washing)
        washing.start()
        washing.join()
        time.sleep(random.uniform(0.03, 0.05))
    else:
      time.sleep(random.uniform(0.6*25, 0.6*30))  
  else:
    time.sleep(random.uniform(0.6*25, 0.6*30)) 
  time.sleep(random.uniform(0.6*25, 0.6*30))
  cook = threading.Thread(target=Cook)
  cook.start()
  cook.join()
  # 18.00
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  if random.randint(0, 3) == 1:
    tv = threading.Thread(target=watchTV)
    tv.start()
    tv.join()
  else:
    time.sleep(random.uniform(0.6*65, 0.6*75))   
  change_clothes = threading.Thread(target=changeClothes)
  change_clothes.start()
  change_clothes.join()
  time.sleep(random.uniform(0.1, 0.2))
  toilet = threading.Thread(target=goToilet)
  toilet.start()
  toilet.join()
  time.sleep(random.uniform(0.6*50, 0.6*60))  
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.6*15, 0.6*20))   
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  time.sleep(random.uniform(0.3, 0.6*1.5))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.6*20, 0.6*25))  
  random_device = random.randint(0, len(BedroomTwo_device_list)-1)
  t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)  
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Heater001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.6*10, 0.6*11))
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Humidifier001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.03, 0.05))
  t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Window001", env, 'User Activity',))
  t12.start()
  pool.append(t12) 
  time.sleep(random.uniform(0.03, 0.05))
  time.sleep(random.uniform(0.03, 0.05))
  if(random.randint(0, 3) == 1):   
    time.sleep(random.uniform(0.6*10, 0.6*11))   
    wash_clothes = threading.Thread(target=washClothes)
    wash_clothes.start()
    wash_clothes.join()
    time.sleep(random.uniform(0.6*20, 0.6*50))  
    collect_clothes = threading.Thread(target=collectClothes)
    collect_clothes.start()
    collect_clothes.join()
  else:
    time.sleep(random.uniform(0.6*50, 0.6*70))  
  random_device = random.randint(0, len(BedroomTwo_device_list)-1)
  t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  stateDecrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  toilet = threading.Thread(target=goToilet)
  toilet.start()
  toilet.join()
  time.sleep(random.uniform(0.1, 0.3))
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  time.sleep(random.uniform(0.3, 0.6*1.5))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.6*50, 0.6*60))  
  t1 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Light001", env, 'User Activity',))
  t1.start()
  pool.append(t1)
  if(random.randint(0, 2) == 1):
    t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Curtain001", env, 'User Activity',))
    t12.start()
    pool.append(t12) 
    time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "TV001", env, 'User Activity',))
  t.start()
  pool.append(t)    
  for item in pool:
    item.join()
    
def weekendpersonTwo(): 
  pool = []
  time.sleep(random.uniform(0.6*60*9, 0.6*60*9.5))
  get_up = threading.Thread(target=getUp, args=("BedroomTwo",))
  get_up.start()
  get_up.join()
  random_device = random.randint(0, len(BedroomTwo_device_list)-1)
  t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.6*1, 0.6*2))
  random_device = random.randint(0, len(BedroomTwo_device_list)-1)
  t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)  
  time.sleep(random.uniform(0.6*25, 0.6*35))
  t2 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t2.start()
  pool.append(t2)
  time.sleep(random.uniform(0.05, 0.1))
  stateDecrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.1, 0.2))
  toilet = threading.Thread(target=goToilet)
  toilet.start()
  toilet.join()
  time.sleep(random.uniform(0.1, 0.15))
  t9 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t9.start()
  pool.append(t9)
  time.sleep(random.uniform(0.03, 0.05))
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  time.sleep(random.uniform(0.6*15, 0.6*20))
  t10 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Light001", env, 'User Activity',))
  t10.start()
  pool.append(t10)
  time.sleep(random.uniform(0.03, 0.05))
  t11 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t11.start()
  pool.append(t11)
  time.sleep(random.uniform(0.05, 0.1))
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  stateDecrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t12.start()
  pool.append(t12)
  time.sleep(random.uniform(0.6*30, 0.6*35))
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)  
  time.sleep(random.uniform(0.1, 0.2))
  cook = threading.Thread(target=Cook)
  cook.start()
  cook.join()
  time.sleep(random.uniform(0.6*30, 0.6*35))
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)  
  time.sleep(random.uniform(0.6*30, 0.6*35))
  cook = threading.Thread(target=Cook)
  cook.start()
  cook.join()
  time.sleep(random.uniform(0.6*15, 0.6*20)) 
  # 出门3小时
  if(random.randint(0, 3) == 1):
    change_clothes = threading.Thread(target=changeClothes)
    change_clothes.start()
    change_clothes.join()
    time.sleep(random.uniform(0.03, 0.05))
    t1 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t1.start()
    pool.append(t1)
    time.sleep(random.uniform(0.03, 0.05))
    stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
    time.sleep(random.uniform(0.3, 0.6*1.5))
    t2 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t2.start()  
    pool.append(t2)
    time.sleep(random.uniform(0.6*60*2.8, 0.6*60*3))
    t3 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t3.start()
    pool.append(t3)
    time.sleep(random.uniform(0.03, 0.05))
    stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
    t4 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t4.start()  
    pool.append(t4)
  else:
    random_device = random.randint(0, len(LivingRoom_device_list)-1)
    t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
    t.start()
    pool.append(t)  
    time.sleep(random.uniform(0.6*60*1, 0.6*1.5))
    washing = threading.Thread(target=Washing)
    washing.start()
    washing.join()
    time.sleep(random.uniform(0.6*60*2, 0.6*1.7))
  # 15.30
  time.sleep(random.uniform(0.1, 0.2))
  cook = threading.Thread(target=Cook)
  cook.start()
  cook.join()
  time.sleep(random.uniform(0.6*15, 0.6*20)) 
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)  
  time.sleep(random.uniform(0.6*40, 0.6*50))   
  if random.randint(0, 3) == 1:
    tv = threading.Thread(target=watchTV)
    tv.start()
    tv.join()
  else:
    time.sleep(random.uniform(0.6*80, 0.6*90))   
  # 18.00
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.6*15, 0.6*20))   
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.6*20, 0.6*30))   
  change_clothes = threading.Thread(target=changeClothes)
  change_clothes.start()
  change_clothes.join()
  time.sleep(random.uniform(0.1, 0.2))
  toilet = threading.Thread(target=goToilet)
  toilet.start()
  toilet.join()
  time.sleep(random.uniform(0.6*20, 0.6*30))  
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  stateIncrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.3, 0.6*1.5))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.6*20, 0.6*25))  
  random_device = random.randint(0, len(BedroomTwo_device_list)-1)
  t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)  
  if(random.randint(0, 3) == 1):   
    time.sleep(random.uniform(0.6*10, 0.6*11))   
    wash_clothes = threading.Thread(target=washClothes)
    wash_clothes.start()
    wash_clothes.join()
    time.sleep(random.uniform(0.6*20, 0.6*50))  
    collect_clothes = threading.Thread(target=collectClothes)
    collect_clothes.start()
    collect_clothes.join()
  else:
    time.sleep(random.uniform(0.6*50, 0.6*70))  
  random_device = random.randint(0, len(BedroomTwo_device_list)-1)
  t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.6*40, 0.6*50))  
  random_device = random.randint(0, len(BedroomTwo_device_list)-1)
  t = threading.Thread(target=BedroomTwo_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomTwo_device_list[0][random_device][1][0],BedroomTwo_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  stateDecrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  toilet = threading.Thread(target=goToilet)
  toilet.start()
  toilet.join()
  time.sleep(random.uniform(0.03, 0.05))
  if(random.randint(0, 3) == 1):
      t12 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Heater001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.1, 0.2))
      stateDecrease(globalFrame.thread_list,"LivingRoom", "Humidity", env)
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Window001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.1, 0.2)) 
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"BedroomTwo", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.6*5, 0.6*8)) 
  if(random.randint(0, 3) == 1):
      t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Heater001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.1, 0.2))
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Humidifier001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.1, 0.2))
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Window001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.1, 0.2)) 
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Window002", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.1, 0.2)) 
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Curtain001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.1, 0.2)) 
  time.sleep(random.uniform(0.6*50, 0.6*60)) 
  t1 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "Light001", env, 'User Activity',))
  t1.start()
  pool.append(t1)
  t1 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomTwo", "TV001", env, 'User Activity',))
  t1.start()
  pool.append(t1)
  
  for item in pool:
    item.join()

def weekendpersonThree():
  pool = []
  time.sleep(random.uniform(0.6*60*9.5, 0.6*60*10))  
  if(random.randint(0, 4) == 1):
    get_up = threading.Thread(target=getUp, args=("BedroomOne",))
    get_up.start()
    get_up.join()
  t2 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t2.start()
  pool.append(t2)
  time.sleep(random.uniform(0.05, 0.1))
  stateDecrease(globalFrame.thread_list,"BedroomOne", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.1, 0.2))
  if(random.randint(0, 2) == 1):   
    start_time = random.uniform(40*0.6, 90*0.6)
    random_event = threading.Thread(target=Reservation, args=(start_time,))
    random_event.start()
    pool.append(random_event)
    if random.randint(0, 50) < 40: 
        time.sleep(start_time - 5*0.6)
        washing = threading.Thread(target=Washing)
        washing.start()
        washing.join()
        time.sleep(random.uniform(0.03, 0.05))
  if random.randint(0, 3) == 1:
    tv = threading.Thread(target=watchTV)
    tv.start()
    tv.join()
  else:
    time.sleep(random.uniform(0.6*80, 0.6*90))   
  if(random.randint(0, 2) == 1):
    get_up = threading.Thread(target=getUp, args=("BedroomOne",))
    get_up.start()
    get_up.join()
  time.sleep(random.uniform(0.1, 0.2))
  t9 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t9.start()
  pool.append(t9)
  time.sleep(random.uniform(0.03, 0.05))
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"BedroomOne", "HumanCount", env)
  time.sleep(random.uniform(0.6*20, 0.6*28))
  t11 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t11.start()
  pool.append(t11)
  time.sleep(random.uniform(0.05, 0.1))
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  stateDecrease(globalFrame.thread_list,"BedroomOne", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t12.start()
  pool.append(t12)
  time.sleep(random.uniform(0.6*40, 0.6*43))
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"BedroomOne", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t.start()  
  pool.append(t)
  time.sleep(random.uniform(0.6*15, 0.6*20))
  random_device = random.randint(0, len(BedroomOne_device_list)-1)
  t = threading.Thread(target=BedroomOne_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomOne_device_list[0][random_device][1][0],BedroomOne_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.6*70, 0.6*75))
  random_device = random.randint(0, len(BedroomOne_device_list)-1)
  t = threading.Thread(target=BedroomOne_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomOne_device_list[0][random_device][1][0],BedroomOne_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.6*25, 0.6*30))
  if(random.randint(0, 5) == 1):
      t12 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Heater001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.6*10, 0.6*11))
      stateDecrease(globalFrame.thread_list,"LivingRoom", "Humidity", env)
      t12 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Window001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.1, 0.2))
  if(random.randint(0, 4) == 1):
      t12 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Humidifier001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.1, 0.2))
  if(random.randint(0, 3) == 1):
    t11 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
    t11.start()
    pool.append(t11)
    time.sleep(random.uniform(0.05, 0.1))
    stateDecrease(globalFrame.thread_list,"BedroomOne", "HumanCount", env)
    stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
    time.sleep(random.uniform(0.03, 0.05))
    t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
    t12.start()
    pool.append(t12)
    time.sleep(random.uniform(0.6*5, 0.6*8))
    change_clothes = threading.Thread(target=changeClothes)
    change_clothes.start()
    change_clothes.join()
    time.sleep(random.uniform(0.03, 0.05))
    t1 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t1.start()
    pool.append(t1)
    time.sleep(random.uniform(0.03, 0.05))
    stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
    time.sleep(random.uniform(0.3, 0.6*1.5))
    t2 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t2.start()  
    pool.append(t2)
    time.sleep(random.uniform(0.6*60*2.8, 0.6*60*3))
    t3 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t3.start()
    pool.append(t3)
    time.sleep(random.uniform(0.03, 0.05))
    stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
    t4 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "LivingRoom", "Door001", env, 'User Activity',))
    t4.start()  
    pool.append(t4)
  else:
    random_device = random.randint(0, len(BedroomOne_device_list)-1)
    t = threading.Thread(target=BedroomOne_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomOne_device_list[0][random_device][1][0],BedroomOne_device_list[0][random_device][1][1], env, 'User Activity',))
    t.start()
    pool.append(t)  
    time.sleep(random.uniform(0.6*60*1, 0.6*1.5))
    toilet = threading.Thread(target=goToilet)
    toilet.start()
    toilet.join()
    time.sleep(random.uniform(0.6*60*2, 0.6*1.7)) 
    t11 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
    t11.start()
    pool.append(t11)
    time.sleep(random.uniform(0.05, 0.1))
    stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
    stateDecrease(globalFrame.thread_list,"BedroomOne", "HumanCount", env)
    time.sleep(random.uniform(0.03, 0.05))
    t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
    t12.start()
    pool.append(t12)
  # 15.30
  time.sleep(random.uniform(0.1, 0.2))
  if(random.randint(0, 3) == 1):
    cook = threading.Thread(target=Cook)
    cook.start()
    cook.join()
    time.sleep(random.uniform(0.6*15, 0.6*20))
  else:
    time.sleep(random.uniform(0.6*35, 0.6*36))
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)  
  time.sleep(random.uniform(0.6*15, 0.6*20))   
  toilet = threading.Thread(target=goToilet)
  toilet.start()
  toilet.join()
  time.sleep(random.uniform(0.6*15, 0.6*20))
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Humidifier001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.1, 0.2))
  time.sleep(random.uniform(0.6*45, 0.6*46))    
  cook = threading.Thread(target=Cook)
  cook.start()
  cook.join()
  # 18.00
  time.sleep(random.uniform(0.6*15, 0.6*20))   
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.6*15, 0.6*20))   
  random_device = random.randint(0, len(LivingRoom_device_list)-1)
  t = threading.Thread(target=LivingRoom_device_list[0][random_device][0], args=(globalFrame.thread_list, LivingRoom_device_list[0][random_device][1][0],LivingRoom_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  time.sleep(random.uniform(0.6*20, 0.6*30))   
  change_clothes = threading.Thread(target=changeClothes)
  change_clothes.start()
  change_clothes.join()
  time.sleep(random.uniform(0.1, 0.2))
  if(random.randint(0, 2) == 1):   
    start_time = random.uniform(40*0.6, 90*0.6)
    random_event = threading.Thread(target=Reservation, args=(start_time,))
    random_event.start()
    pool.append(random_event)
    if random.randint(0, 50) < 40: 
        time.sleep(start_time - 5*0.6)
        washing = threading.Thread(target=Washing)
        washing.start()
        washing.join()
        time.sleep(random.uniform(0.03, 0.05))
    else:
      time.sleep(random.uniform(0.6*25, 0.6*30))  
  else:
    washing = threading.Thread(target=Washing)
    washing.start()
    washing.join()
  time.sleep(random.uniform(0.6*20, 0.6*30))  
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  stateIncrease(globalFrame.thread_list,"BedroomOne", "HumanCount", env)
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.6*20, 0.6*25))  
  random_device = random.randint(0, len(BedroomOne_device_list)-1)
  t = threading.Thread(target=BedroomOne_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomOne_device_list[0][random_device][1][0],BedroomOne_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)  
  time.sleep(random.uniform(0.6*50, 0.6*70))  
  random_device = random.randint(0, len(BedroomOne_device_list)-1)
  t = threading.Thread(target=BedroomOne_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomOne_device_list[0][random_device][1][0],BedroomOne_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)    
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  stateDecrease(globalFrame.thread_list,"BedroomOne", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  toilet = threading.Thread(target=goToilet)
  toilet.start()
  toilet.join()
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOn, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t.start()
  pool.append(t)
  time.sleep(random.uniform(0.03, 0.05))
  stateDecrease(globalFrame.thread_list,"LivingRoom", "HumanCount", env)
  stateIncrease(globalFrame.thread_list,"BedroomOne", "HumanCount", env)
  time.sleep(random.uniform(0.03, 0.05))
  t = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Door001", env, 'User Activity',))
  t.start() 
  pool.append(t)
  time.sleep(random.uniform(0.6*40, 0.6*50))  
  random_device = random.randint(0, len(BedroomOne_device_list)-1)
  t = threading.Thread(target=BedroomOne_device_list[0][random_device][0], args=(globalFrame.thread_list, BedroomOne_device_list[0][random_device][1][0],BedroomOne_device_list[0][random_device][1][1], env, 'User Activity',))
  t.start()
  pool.append(t)  
  time.sleep(random.uniform(0.1, 0.2))
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Humidifier001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.1, 0.2))
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Window001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.1, 0.2))
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Heater001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.1, 0.2))
  if(random.randint(0, 2) == 1):
      t12 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Curtain001", env, 'User Activity',))
      t12.start()
      pool.append(t12) 
      time.sleep(random.uniform(0.1, 0.2)) 
  time.sleep(random.uniform(0.6*50, 0.6*60))  
  t1 = threading.Thread(target=deviceOff, args=(globalFrame.thread_list, "BedroomOne", "Light001", env, 'User Activity',))
  t1.start()
  pool.append(t1)
  
  for item in pool:
    item.join()
